In [2]:
print("Hello Talib")

Hello Talib

# Data Extract

In [3]:
import oracledb

conn = oracledb.connect(
    user = "hr",
    password = "hr",
    host = "192.168.101.190",
    port = 1521,
    service_name = "finiprm"
)

cur = conn.cursor()
print("connected ")

connected

In [4]:
cur.execute("""
        SELECT table_name
            from all_tables
            where owner = 'HR'
            order by table_name
            """
)

for t in cur.fetchall():
    print(t[0])

COUNTRIES
DEPARTMENTS
EMP1
EMPLOYEES
GLOBAL_SUPERSTORE2
JOBS
JOB_HISTORY
LOCATIONS
REGIONS
TALIB

In [ ]:
import pandas as pd 

query = "select * from GLOBAL_SUPERSTORE2"
df = pd.read_sql(query, conn)

C:\Users\Work\AppData\Local\Temp\ipykernel_8392\3949833275.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,3/13/2014,3/13/2014,Same Day,VM-2168591,Valerie Mitchum,Home Office,None,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black","$2,570.87",11,0.5,"-$2,211.17",520.89,High
1,32648,CA-2014-AS10045140-41727,3/29/2014,4/1/2014,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,$31.40,2,0,$7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,4/5/2013,4/5/2013,Same Day,DM-1352548,Don Miller,Corporate,None,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID","$2,875.77",9,0.5,"-$1,783.08",516.63,High
3,14721,ES-2013-NM18520120-41634,12/26/2013,12/28/2013,Second Class,NM-18520120,Neoma Murray,Consumer,None,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal","$1,741.80",4,0,$261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,4/18/2014,4/19/2014,First Class,LC-168857,Lena Creighton,Consumer,None,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser","$1,601.64",5,0.1,$587.19,511.47,Critical

In [46]:
df.head()

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,SHIPPING_COST,ORDER_PRIORITY,TOTAL_PRICE,BEST_SELLING,COUNTRY_RANK,YEAR,DAY_NAME,DELIVERY_DAYS,DATE_ID,PAYMENT_ID
0,11743,IT-2014-VM2168591-41711,2014-03-13,2014-03-13,Same Day,VM-2168591,Valerie Mitchum,Home Office,0,Bergen op Zoom,...,520.89,High,28279.57,83,1.0,2014,Thursday,0 days,0,0
1,32648,CA-2014-AS10045140-41727,2014-03-29,2014-04-01,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,3.81,Medium,62.80,12,3151.0,2014,Saturday,3 days,1,1
2,17522,ES-2013-DM1352548-41369,2013-04-05,2013-04-05,Same Day,DM-1352548,Don Miller,Corporate,0,Hanover,...,516.63,High,25881.93,38,5.0,2013,Friday,0 days,2,2
3,14721,ES-2013-NM18520120-41634,2013-12-26,2013-12-28,Second Class,NM-18520120,Neoma Murray,Consumer,0,Vigo,...,515.24,Critical,6967.20,68,42.0,2013,Thursday,2 days,3,3
4,29629,IN-2014-LC168857-41747,2014-04-18,2014-04-19,First Class,LC-168857,Lena Creighton,Consumer,0,Sydney,...,511.47,Critical,8008.20,55,124.0,2014,Friday,1 days,4,4

In [6]:
df.dtypes

ROW_ID            object
ORDER_ID          object
ORDER_DATE        object
SHIP_DATE         object
SHIP_MODE         object
CUSTOMER_ID       object
CUSTOMER_NAME     object
SEGMENT           object
POSTAL_CODE       object
CITY              object
STATE             object
COUNTRY           object
REGION            object
MARKET            object
PRODUCT_ID        object
CATEGORY          object
SUB_CATEGORY      object
PRODUCT_NAME      object
SALES             object
QUANTITY          object
DISCOUNT          object
PROFIT            object
SHIPPING_COST     object
ORDER_PRIORITY    object
dtype: object

# Data Tranformation

In [7]:
df.isna().sum()

ROW_ID                0
ORDER_ID              0
ORDER_DATE            0
SHIP_DATE             0
SHIP_MODE             0
CUSTOMER_ID           0
CUSTOMER_NAME         0
SEGMENT               0
POSTAL_CODE       41296
CITY                  0
STATE                 0
COUNTRY               0
REGION                0
MARKET                0
PRODUCT_ID            0
CATEGORY              0
SUB_CATEGORY          0
PRODUCT_NAME          0
SALES                 0
QUANTITY              0
DISCOUNT              0
PROFIT                0
SHIPPING_COST         0
ORDER_PRIORITY        0
dtype: int64

In [8]:
df["ROW_ID"] = df["ROW_ID"].astype(int)

In [9]:
df.ORDER_ID

0         IT-2014-VM2168591-41711
1        CA-2014-AS10045140-41727
2         ES-2013-DM1352548-41369
3        ES-2013-NM18520120-41634
4          IN-2014-LC168857-41747
                   ...
51285    CA-2012-TS21370140-41209
51286      ID-2013-BG110357-41276
51287    CA-2015-TS21370140-42283
51288    CA-2012-TS21370140-41209
51289    CA-2012-TS21370140-41209
Name: ORDER_ID, Length: 51290, dtype: object

In [10]:
df.ORDER_DATE

0         3/13/2014
1         3/29/2014
2          4/5/2013
3        12/26/2013
4         4/18/2014
            ...
51285    10/27/2012
51286      1/2/2013
51287     10/6/2015
51288    10/27/2012
51289    10/27/2012
Name: ORDER_DATE, Length: 51290, dtype: object

In [11]:
df["ORDER_DATE"] = pd.to_datetime(df["ORDER_DATE"])

In [12]:
df["ORDER_DATE"].isna().sum()

np.int64(0)

In [13]:
df["SHIP_DATE"] = pd.to_datetime(df["SHIP_DATE"])

In [14]:
df.SHIP_DATE.isna().sum()

np.int64(0)

In [15]:
df["SHIP_MODE"] = df["SHIP_MODE"].astype(str)

In [16]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY'],
      dtype='object')

In [17]:
df.POSTAL_CODE = df["POSTAL_CODE"].fillna(0)

In [18]:
df["SALES"] = (df["SALES"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
)

In [19]:
df.QUANTITY = df.QUANTITY.astype(int)

In [20]:
df.DISCOUNT = df.DISCOUNT.astype(float)

In [21]:

df["PROFIT"] = (df["PROFIT"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
    )

In [22]:
df['SHIPPING_COST'] = df['SHIPPING_COST'].astype(float)

In [ ]:
df.head()

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,2014-03-13,2014-03-13,Same Day,VM-2168591,Valerie Mitchum,Home Office,0,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black",2570.87,11,0.5,-2211.17,520.89,High
1,32648,CA-2014-AS10045140-41727,2014-03-29,2014-04-01,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,31.40,2,0.0,7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,2013-04-05,2013-04-05,Same Day,DM-1352548,Don Miller,Corporate,0,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID",2875.77,9,0.5,-1783.08,516.63,High
3,14721,ES-2013-NM18520120-41634,2013-12-26,2013-12-28,Second Class,NM-18520120,Neoma Murray,Consumer,0,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal",1741.80,4,0.0,261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,2014-04-18,2014-04-19,First Class,LC-168857,Lena Creighton,Consumer,0,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser",1601.64,5,0.1,587.19,511.47,Critical

In [24]:
df = df.drop_duplicates(
    subset=['ORDER_ID'], 
    keep='first'
    ).reset_index(drop=True)

In [25]:
df.shape

(25728, 24)

# Data Preparation

In [26]:
df["TOTAL_PRICE"] = (df['SALES'] * df['QUANTITY'])

In [27]:
df[['TOTAL_PRICE']]

       TOTAL_PRICE
0         28279.57
1            62.80
2         25881.93
3          6967.20
4          8008.20
...            ...
25723         5.70
25724         4.46
25725         6.67
25726      1469.86
25727        27.15

[25728 rows x 1 columns]

In [28]:
df['BEST_SELLING'] = (
    df.groupby('PRODUCT_NAME')['QUANTITY']
      .transform('sum')
)

In [29]:
df[['PRODUCT_NAME','BEST_SELLING']].sort_values(by='BEST_SELLING', ascending=True)

                                            PRODUCT_NAME  BEST_SELLING
18319  Sanford Colorific Eraseable Coloring Pencils, ...             1
15729  ClearSounds CSC500 Amplified Spirit Phone Cord...             1
18557         Avery Personal Creations Heavyweight Cards             1
18161  Executive Impressions 14" Two-Color Numerals W...             1
15034                         Avery Hanging File Binders             1
...                                                  ...           ...
19948                                            Staples           399
6633                                             Staples           399
2859                                             Staples           399
50                                               Staples           399
21769                                            Staples           399

[25728 rows x 2 columns]

In [30]:
df['COUNTRY_RANK'] = (df.groupby('COUNTRY')['TOTAL_PRICE']
                      .rank(method="dense", ascending=False))

In [31]:
(df[['COUNTRY','COUNTRY_RANK']].sort_values(by='COUNTRY_RANK')).head(10)

           COUNTRY  COUNTRY_RANK
34     Afghanistan           1.0
70         Uruguay           1.0
0      Netherlands           1.0
5112       Croatia           1.0
12082      Burundi           1.0
2795        Jordan           1.0
147      Singapore           1.0
3203        Panama           1.0
4779       Bahrain           1.0
16198      Armenia           1.0

In [32]:
df['YEAR'] = df['ORDER_DATE'].dt.year

In [33]:
df['DAY_NAME'] = df['ORDER_DATE'].dt.day_name()

In [34]:
df['DELIVERY_DAYS'] = df['SHIP_DATE'] - df['ORDER_DATE']

In [35]:
df['DATE_ID'] = df.index
df['PAYMENT_ID'] = df.index

# Fact and Dimension Schema 
* Dimension Table

In [36]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY', 'TOTAL_PRICE',
       'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME', 'DELIVERY_DAYS',
       'DATE_ID', 'PAYMENT_ID'],
      dtype='object')

### Customer Dimension

In [37]:
dim_Customer = (
    df[[
        'CUSTOMER_ID',
        'CUSTOMER_NAME',
        'SEGMENT',
        'POSTAL_CODE',
        'CITY',
        'STATE',
        'COUNTRY',
        'REGION',
        'MARKET',
        'COUNTRY_RANK'
    ]]
    
)
dim_Customer

,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,STATE,COUNTRY,REGION,MARKET,COUNTRY_RANK
0,VM-2168591,Valerie Mitchum,Home Office,0,Bergen op Zoom,North Brabant,Netherlands,Western Europe,Europe,1.0
1,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,Virginia,United States,Southern US,USCA,3151.0
2,DM-1352548,Don Miller,Corporate,0,Hanover,Lower Saxony,Germany,Western Europe,Europe,5.0
3,NM-18520120,Neoma Murray,Consumer,0,Vigo,Galicia,Spain,Southern Europe,Europe,42.0
4,LC-168857,Lena Creighton,Consumer,0,Sydney,New South Wales,Australia,Oceania,Asia Pacific,124.0
...,...,...,...,...,...,...,...,...,...,...
25723,MA-799569,Michelle Arnett,Home Office,0,Mombasa,Coast,Kenya,Eastern Africa,Africa,56.0
25724,RB-1933082,Randy Bradley,Consumer,0,Tijuana,Baja California,Mexico,Central America,LATAM,1221.0
25725,SC-2038098,Shahid Collister,Consumer,0,Panama City,Panama,Panama,Central America,LATAM,193.0
25726,TS-213701404,Todd Sumrall,Corporate,85023,Phoenix,Arizona,United States,Western US,USCA,1010.0
25727,AH-1058591,Angele Hood,Consumer,0,Zeist,Utrecht,Netherlands,Western Europe,Europe,199.0

In [38]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY', 'TOTAL_PRICE',
       'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME', 'DELIVERY_DAYS',
       'DATE_ID', 'PAYMENT_ID'],
      dtype='object')

In [39]:
dim_product = (
    df[[
        'PRODUCT_ID',
        'PRODUCT_NAME',
        'CATEGORY',
        'SUB_CATEGORY',
        'ORDER_PRIORITY',
        'BEST_SELLING',
        'QUANTITY',
        'SHIP_MODE'
    ]]
)

dim_product

,PRODUCT_ID,PRODUCT_NAME,CATEGORY,SUB_CATEGORY,ORDER_PRIORITY,BEST_SELLING,QUANTITY,SHIP_MODE
0,FUR-CH-5442,"Office Star Executive Leather Armchair, Black",Furniture,Chairs,High,83,11,Same Day
1,OFF-ST-4516,Hanging Personal Folder File,Office Supplies,Storage,Medium,12,2,First Class
2,TEC-PH-3149,"Apple Smart Phone, with Caller ID",Technology,Phones,High,38,9,Same Day
3,FUR-BO-5948,"Sauder Classic Bookcase, Metal",Furniture,Bookcases,Critical,68,4,Second Class
4,TEC-CO-6012,"Sharp Wireless Fax, Laser",Technology,Copiers,Critical,55,5,First Class
...,...,...,...,...,...,...,...,...
25723,OFF-BI-3736,"Cardinal Hole Reinforcements, Recycled",Office Supplies,Binders,Medium,32,1,Standard Class
25724,OFF-BI-3294,"Avery Index Tab, Durable",Office Supplies,Binders,High,30,1,Standard Class
25725,OFF-FA-6185,"Stockwell Clamps, Assorted Sizes",Office Supplies,Fasteners,Medium,73,1,Standard Class
25726,FUR-BO-3409,Bestar Classic Bookcase,Furniture,Bookcases,High,26,7,First Class
25727,OFF-BI-6398,"Wilson Jones Hole Reinforcements, Durable",Office Supplies,Binders,High,32,3,Second Class

In [40]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY', 'TOTAL_PRICE',
       'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME', 'DELIVERY_DAYS',
       'DATE_ID', 'PAYMENT_ID'],
      dtype='object')

In [41]:
dim_date = (
    df[[
        'DATE_ID',
        'ORDER_DATE',
        'SHIP_DATE',
        'YEAR',
        'DAY_NAME',
        'DELIVERY_DAYS',
        'SHIPPING_COST',
        
    ]]
)
dim_date

,DATE_ID,ORDER_DATE,SHIP_DATE,YEAR,DAY_NAME,DELIVERY_DAYS,SHIPPING_COST
0,0,2014-03-13,2014-03-13,2014,Thursday,0 days,520.890
1,1,2014-03-29,2014-04-01,2014,Saturday,3 days,3.810
2,2,2013-04-05,2013-04-05,2013,Friday,0 days,516.630
3,3,2013-12-26,2013-12-28,2013,Thursday,2 days,515.240
4,4,2014-04-18,2014-04-19,2014,Friday,1 days,511.470
...,...,...,...,...,...,...,...
25723,25723,2014-09-06,2014-09-13,2014,Saturday,7 days,1.250
25724,25724,2012-10-24,2012-10-28,2012,Wednesday,4 days,1.206
25725,25725,2014-05-16,2014-05-21,2014,Friday,5 days,1.204
25726,25726,2015-05-12,2015-05-14,2015,Tuesday,2 days,30.170
25727,25727,2015-07-01,2015-07-03,2015,Wednesday,2 days,1.200

In [42]:
dim_Payments = (
    df[[
        'PAYMENT_ID',
        'SALES',
        'PROFIT',
        'DISCOUNT',
        'TOTAL_PRICE'
    ]]
)
dim_Payments.head()

   PAYMENT_ID    SALES   PROFIT  DISCOUNT  TOTAL_PRICE
0           0  2570.87 -2211.17       0.5     28279.57
1           1    31.40     7.85       0.0        62.80
2           2  2875.77 -1783.08       0.5     25881.93
3           3  1741.80   261.24       0.0      6967.20
4           4  1601.64   587.19       0.1      8008.20

## Fact Table

In [43]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY', 'TOTAL_PRICE',
       'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME', 'DELIVERY_DAYS',
       'DATE_ID', 'PAYMENT_ID'],
      dtype='object')

In [44]:
Fact_table = (
    df[[
        'ROW_ID',
        'CUSTOMER_ID',
        'PRODUCT_ID',
        'DATE_ID',
        'PAYMENT_ID'
    ]]
)
Fact_table.head()

   ROW_ID   CUSTOMER_ID   PRODUCT_ID  DATE_ID  PAYMENT_ID
0   11743    VM-2168591  FUR-CH-5442        0           0
1   32648  AS-100451408  OFF-ST-4516        1           1
2   17522    DM-1352548  TEC-PH-3149        2           2
3   14721   NM-18520120  FUR-BO-5948        3           3
4   29629     LC-168857  TEC-CO-6012        4           4

In [45]:
dim_Customer.to_csv("CUSTOMERS.csv", index=False)
dim_date.to_csv("DATES.csv", index=False)
dim_product.to_csv("PRODUCTS.csv", index=False)
dim_Payments.to_csv("PAYMENTS.csv", index=False)