In [72]:
print("Hello Talib")

Hello Talib

In [ ]:
import oracledb

conn = oracledb.connect(
    user = "hr",
    password = "hr",
    host = "192.168.101.190",
    port = 1521,
    service_name = "finiprm"
)

cur = conn.cursor()
print("connected ")

connected

In [74]:
cur.execute("""
        SELECT table_name
            from all_tables
            where owner = 'HR'
            order by table_name
            """
)

for t in cur.fetchall():
    print(t[0])

COUNTRIES
DEPARTMENTS
EMP1
EMPLOYEES
GLOBAL_SUPERSTORE2
JOBS
JOB_HISTORY
LOCATIONS
REGIONS
TALIB

In [75]:
import pandas as pd 

query = "select * from GLOBAL_SUPERSTORE2"
df = pd.read_sql(query, conn)
df

C:\Users\Work\AppData\Local\Temp\ipykernel_4448\1132302301.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,3/13/2014,3/13/2014,Same Day,VM-2168591,Valerie Mitchum,Home Office,None,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black","$2,570.87",11,0.5,"-$2,211.17",520.89,High
1,32648,CA-2014-AS10045140-41727,3/29/2014,4/1/2014,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,$31.40,2,0,$7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,4/5/2013,4/5/2013,Same Day,DM-1352548,Don Miller,Corporate,None,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID","$2,875.77",9,0.5,"-$1,783.08",516.63,High
3,14721,ES-2013-NM18520120-41634,12/26/2013,12/28/2013,Second Class,NM-18520120,Neoma Murray,Consumer,None,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal","$1,741.80",4,0,$261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,4/18/2014,4/19/2014,First Class,LC-168857,Lena Creighton,Consumer,None,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser","$1,601.64",5,0.1,$587.19,511.47,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,35143,CA-2012-TS21370140-41209,10/27/2012,10/30/2012,First Class,TS-213701404,Todd Sumrall,Corporate,90049,Los Angeles,...,OFF-ST-4088,Office Supplies,Storage,Eldon Portable Mobile Manager,$141.40,5,0,$38.18,14.96,High
51286,25579,ID-2013-BG110357-41276,1/2/2013,1/6/2013,Standard Class,BG-110357,Barry Gonzalez,Consumer,None,Brisbane,...,OFF-EN-3655,Office Supplies,Envelopes,"Cameo Business Envelopes, Security-Tint",$15.26,1,0.1,-$0.35,1.2,Medium
51287,37635,CA-2015-TS21370140-42283,10/6/2015,10/10/2015,Standard Class,TS-213701406,Todd Sumrall,Corporate,10035,New York City,...,TEC-PH-5828,Technology,Phones,Samsung HM1900 Bluetooth Headset,$87.80,4,0,$43.90,4.69,Medium
51288,35139,CA-2012-TS21370140-41209,10/27/2012,10/30/2012,First Class,TS-213701404,Todd Sumrall,Corporate,90049,Los Angeles,...,OFF-BI-3302,Office Supplies,Binders,Avery Non-Stick Binders,$7.18,2,0.2,$2.25,1.57,High
51289,35140,CA-2012-TS21370140-41209,10/27/2012,10/30/2012,First Class,TS-213701404,Todd Sumrall,Corporate,90049,Los Angeles,...,OFF-SU-5981,Office Supplies,Supplies,Serrated Blade or Curved Handle Hand Letter Op...,$6.28,2,0,$0.06,1.41,High

In [96]:
df.dtypes

ROW_ID                     int64
ORDER_ID                  object
ORDER_DATE        datetime64[ns]
SHIP_DATE         datetime64[ns]
SHIP_MODE                 object
CUSTOMER_ID               object
CUSTOMER_NAME             object
SEGMENT                   object
POSTAL_CODE               object
CITY                      object
STATE                     object
COUNTRY                   object
REGION                    object
MARKET                    object
PRODUCT_ID                object
CATEGORY                  object
SUB_CATEGORY              object
PRODUCT_NAME              object
SALES                    float64
QUANTITY                   int64
DISCOUNT                 float64
PROFIT                   float64
SHIPPING_COST            float64
ORDER_PRIORITY            object
dtype: object

In [77]:
df.isna().sum()

ROW_ID                0
ORDER_ID              0
ORDER_DATE            0
SHIP_DATE             0
SHIP_MODE             0
CUSTOMER_ID           0
CUSTOMER_NAME         0
SEGMENT               0
POSTAL_CODE       41296
CITY                  0
STATE                 0
COUNTRY               0
REGION                0
MARKET                0
PRODUCT_ID            0
CATEGORY              0
SUB_CATEGORY          0
PRODUCT_NAME          0
SALES                 0
QUANTITY              0
DISCOUNT              0
PROFIT                0
SHIPPING_COST         0
ORDER_PRIORITY        0
dtype: int64

In [78]:
df["ROW_ID"] = df["ROW_ID"].astype(int)

In [79]:
df.ORDER_ID

0         IT-2014-VM2168591-41711
1        CA-2014-AS10045140-41727
2         ES-2013-DM1352548-41369
3        ES-2013-NM18520120-41634
4          IN-2014-LC168857-41747
                   ...
51285    CA-2012-TS21370140-41209
51286      ID-2013-BG110357-41276
51287    CA-2015-TS21370140-42283
51288    CA-2012-TS21370140-41209
51289    CA-2012-TS21370140-41209
Name: ORDER_ID, Length: 51290, dtype: object

In [80]:
df.ORDER_DATE

0         3/13/2014
1         3/29/2014
2          4/5/2013
3        12/26/2013
4         4/18/2014
            ...
51285    10/27/2012
51286      1/2/2013
51287     10/6/2015
51288    10/27/2012
51289    10/27/2012
Name: ORDER_DATE, Length: 51290, dtype: object

In [81]:
df["ORDER_DATE"] = pd.to_datetime(df["ORDER_DATE"])

In [82]:
df["ORDER_DATE"].isna().sum()

np.int64(0)

In [83]:
df["SHIP_DATE"] = pd.to_datetime(df["SHIP_DATE"])

In [84]:
df.SHIP_DATE.isna().sum()

np.int64(0)

In [85]:
df["SHIP_MODE"] = df["SHIP_MODE"].astype(str)

In [86]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY'],
      dtype='object')

In [87]:
df.POSTAL_CODE = df["POSTAL_CODE"].fillna(0)

In [88]:
df["SALES"] = (df["SALES"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
)

In [89]:
df.QUANTITY = df.QUANTITY.astype(int)

In [90]:
df.DISCOUNT = df.DISCOUNT.astype(float)

In [ ]:

df["PROFIT"] = (df["PROFIT"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
    )

0       -2211.17
1           7.85
2       -1783.08
3         261.24
4         587.19
          ...
51285      38.18
51286      -0.35
51287      43.90
51288       2.25
51289       0.06
Name: PROFIT, Length: 51290, dtype: float64

In [ ]:
df['SHIPPING_COST'] = df['SHIPPING_COST'].astype(float)

0        520.89
1          3.81
2        516.63
3        515.24
4        511.47
          ...
51285     14.96
51286      1.20
51287      4.69
51288      1.57
51289      1.41
Name: SHIPPING_COST, Length: 51290, dtype: float64

In [98]:
df.head(10)

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,2014-03-13,2014-03-13,Same Day,VM-2168591,Valerie Mitchum,Home Office,0,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black",2570.87,11,0.5,-2211.17,520.89,High
1,32648,CA-2014-AS10045140-41727,2014-03-29,2014-04-01,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,31.40,2,0.0,7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,2013-04-05,2013-04-05,Same Day,DM-1352548,Don Miller,Corporate,0,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID",2875.77,9,0.5,-1783.08,516.63,High
3,14721,ES-2013-NM18520120-41634,2013-12-26,2013-12-28,Second Class,NM-18520120,Neoma Murray,Consumer,0,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal",1741.80,4,0.0,261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,2014-04-18,2014-04-19,First Class,LC-168857,Lena Creighton,Consumer,0,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser",1601.64,5,0.1,587.19,511.47,Critical
5,25868,IN-2012-RO1978027-41052,2012-05-23,2012-05-25,Second Class,RO-1978027,Rose O'Brian,Consumer,0,Gaoyou,...,OFF-AP-4738,Office Supplies,Appliances,"Hoover Refrigerator, White",3670.80,7,0.0,367.08,510.72,High
6,33131,CA-2015-AS10045140-42218,2015-08-02,2015-08-08,Standard Class,AS-100451402,Aaron Smayling,Corporate,78745,Austin,...,OFF-PA-6557,Office Supplies,Paper,Xerox 1998,36.29,7,0.2,12.70,1.99,Medium
7,19559,ES-2014-EM1406548-41775,2014-05-16,2014-05-20,Second Class,EM-1406548,Erin Mull,Consumer,0,Bremen,...,TEC-CO-4593,Technology,Copiers,"Hewlett Wireless Fax, Laser",1900.95,5,0.0,589.20,506.89,High
8,32638,CA-2015-AS10045140-42007,2015-01-03,2015-01-05,First Class,AS-100451408,Aaron Smayling,Corporate,28540,Jacksonville,...,OFF-BI-3185,Office Supplies,Binders,"Avery 3 1/2"" Diskette Storage Pages, 10/Pack",15.66,5,0.7,-12.53,1.56,High
9,14070,IT-2012-ON1871545-40955,2012-02-16,2012-02-19,Second Class,ON-1871545,Odella Nelson,Corporate,0,Muret,...,FUR-CH-5774,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",4544.10,11,0.1,1868.13,506.27,Medium