In [117]:
print("Hello Talib")

Hello Talib

# Data Extract

In [118]:
import oracledb

conn = oracledb.connect(
    user = "hr",
    password = "hr",
    host = "192.168.101.190",
    port = 1521,
    service_name = "finiprm"
)

cur = conn.cursor()
print("connected ")

connected

In [119]:
cur.execute("""
        SELECT table_name
            from all_tables
            where owner = 'HR'
            order by table_name
            """
)

for t in cur.fetchall():
    print(t[0])

COUNTRIES
DEPARTMENTS
EMP1
EMPLOYEES
GLOBAL_SUPERSTORE2
JOBS
JOB_HISTORY
LOCATIONS
REGIONS
TALIB

In [120]:
import pandas as pd 

query = "select * from GLOBAL_SUPERSTORE2"
df = pd.read_sql(query, conn)
df.head(5)

C:\Users\Work\AppData\Local\Temp\ipykernel_12236\3949833275.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,3/13/2014,3/13/2014,Same Day,VM-2168591,Valerie Mitchum,Home Office,None,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black","$2,570.87",11,0.5,"-$2,211.17",520.89,High
1,32648,CA-2014-AS10045140-41727,3/29/2014,4/1/2014,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,$31.40,2,0,$7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,4/5/2013,4/5/2013,Same Day,DM-1352548,Don Miller,Corporate,None,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID","$2,875.77",9,0.5,"-$1,783.08",516.63,High
3,14721,ES-2013-NM18520120-41634,12/26/2013,12/28/2013,Second Class,NM-18520120,Neoma Murray,Consumer,None,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal","$1,741.80",4,0,$261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,4/18/2014,4/19/2014,First Class,LC-168857,Lena Creighton,Consumer,None,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser","$1,601.64",5,0.1,$587.19,511.47,Critical

In [121]:
df.dtypes

ROW_ID            object
ORDER_ID          object
ORDER_DATE        object
SHIP_DATE         object
SHIP_MODE         object
CUSTOMER_ID       object
CUSTOMER_NAME     object
SEGMENT           object
POSTAL_CODE       object
CITY              object
STATE             object
COUNTRY           object
REGION            object
MARKET            object
PRODUCT_ID        object
CATEGORY          object
SUB_CATEGORY      object
PRODUCT_NAME      object
SALES             object
QUANTITY          object
DISCOUNT          object
PROFIT            object
SHIPPING_COST     object
ORDER_PRIORITY    object
dtype: object

# Data Tranformation

In [122]:
df.isna().sum()

ROW_ID                0
ORDER_ID              0
ORDER_DATE            0
SHIP_DATE             0
SHIP_MODE             0
CUSTOMER_ID           0
CUSTOMER_NAME         0
SEGMENT               0
POSTAL_CODE       41296
CITY                  0
STATE                 0
COUNTRY               0
REGION                0
MARKET                0
PRODUCT_ID            0
CATEGORY              0
SUB_CATEGORY          0
PRODUCT_NAME          0
SALES                 0
QUANTITY              0
DISCOUNT              0
PROFIT                0
SHIPPING_COST         0
ORDER_PRIORITY        0
dtype: int64

In [123]:
df["ROW_ID"] = df["ROW_ID"].astype(int)

In [124]:
df.ORDER_ID

0         IT-2014-VM2168591-41711
1        CA-2014-AS10045140-41727
2         ES-2013-DM1352548-41369
3        ES-2013-NM18520120-41634
4          IN-2014-LC168857-41747
                   ...
51285    CA-2012-TS21370140-41209
51286      ID-2013-BG110357-41276
51287    CA-2015-TS21370140-42283
51288    CA-2012-TS21370140-41209
51289    CA-2012-TS21370140-41209
Name: ORDER_ID, Length: 51290, dtype: object

In [125]:
df.ORDER_DATE

0         3/13/2014
1         3/29/2014
2          4/5/2013
3        12/26/2013
4         4/18/2014
            ...
51285    10/27/2012
51286      1/2/2013
51287     10/6/2015
51288    10/27/2012
51289    10/27/2012
Name: ORDER_DATE, Length: 51290, dtype: object

In [126]:
df["ORDER_DATE"] = pd.to_datetime(df["ORDER_DATE"])

In [127]:
df["ORDER_DATE"].isna().sum()

np.int64(0)

In [128]:
df["SHIP_DATE"] = pd.to_datetime(df["SHIP_DATE"])

In [129]:
df.SHIP_DATE.isna().sum()

np.int64(0)

In [130]:
df["SHIP_MODE"] = df["SHIP_MODE"].astype(str)

In [131]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY'],
      dtype='object')

In [132]:
df.POSTAL_CODE = df["POSTAL_CODE"].fillna(0)

In [133]:
df["SALES"] = (df["SALES"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
)

In [134]:
df.QUANTITY = df.QUANTITY.astype(int)

In [135]:
df.DISCOUNT = df.DISCOUNT.astype(float)

In [136]:

df["PROFIT"] = (df["PROFIT"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
    )

In [137]:
df['SHIPPING_COST'] = df['SHIPPING_COST'].astype(float)

In [138]:
df.head(5)

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,2014-03-13,2014-03-13,Same Day,VM-2168591,Valerie Mitchum,Home Office,0,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black",2570.87,11,0.5,-2211.17,520.89,High
1,32648,CA-2014-AS10045140-41727,2014-03-29,2014-04-01,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,31.40,2,0.0,7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,2013-04-05,2013-04-05,Same Day,DM-1352548,Don Miller,Corporate,0,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID",2875.77,9,0.5,-1783.08,516.63,High
3,14721,ES-2013-NM18520120-41634,2013-12-26,2013-12-28,Second Class,NM-18520120,Neoma Murray,Consumer,0,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal",1741.80,4,0.0,261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,2014-04-18,2014-04-19,First Class,LC-168857,Lena Creighton,Consumer,0,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser",1601.64,5,0.1,587.19,511.47,Critical

# Data Preparation

In [139]:
df["TOTAL_PRICE"] = (df['SALES'] * df['QUANTITY'])

In [140]:
df[['TOTAL_PRICE']]

       TOTAL_PRICE
0         28279.57
1            62.80
2         25881.93
3          6967.20
4          8008.20
...            ...
51285       707.00
51286        15.26
51287       351.20
51288        14.36
51289        12.56

[51290 rows x 1 columns]

In [141]:
df['BEST_SELLING'] = (
    df.groupby('PRODUCT_NAME')['QUANTITY']
      .transform('sum')
)

In [142]:
df[['PRODUCT_NAME','BEST_SELLING']].sort_values(by='BEST_SELLING', ascending=False)

                                            PRODUCT_NAME  BEST_SELLING
18414                                            Staples           876
26983                                            Staples           876
33542                                            Staples           876
49845                                            Staples           876
35122                                            Staples           876
...                                                  ...           ...
24739  Global Enterprise Series Seating Low-Back Swiv...             1
47736       Chromcraft Training Table, Adjustable Height             1
26657                Penpower WorldCard Pro Card Scanner             1
48456  Bush Saratoga Collection 5-Shelf Bookcase, Han...             1
27174                                           Xerox 20             1

[51290 rows x 2 columns]

In [143]:
df['COUNTRY_RANK'] = df.groupby('COUNTRY')['TOTAL_PRICE'].rank(method="dense", ascending=False)

In [144]:
(df[['COUNTRY','COUNTRY_RANK']].sort_values(by='COUNTRY_RANK')).head(10)

                     COUNTRY  COUNTRY_RANK
91                     China           1.0
23513              Sri Lanka           1.0
752    Republic of the Congo           1.0
3301                 Ukraine           1.0
302                Argentina           1.0
1265                 Algeria           1.0
327                  Lesotho           1.0
65            United Kingdom           1.0
969                    Ghana           1.0
12174                  Spain           1.0